<?php
#NOMBRES DIRECTORIOS DE ALMACENAMIENTO LOCAL Y REMOTO
$FACTRONICA["ENVIARSII"]="1";# 1=SI 0=NO
$FACTRONICA["ALMACENLOCAL"]="../home/111111111";# NOMBRE DE LA CARPETA LOCAL DE ALMACENAMIENTO
$FACTRONICA["ALMACENREMOTO"]="../home/111111111";# NOMBRE DE LA CARPETA REMOTA DE ALMACENAMIENTO
$FACTRONICA["ARCHIVOPLANO"]="datos_cesion_dte.txt";# NOMBRE DEL ARCHIVO PLANO QUE ESTA ENVIANDO
# 
# 
# 
#NOMBRE DEL ARCHIVO XML A CEDER (SOLO EL DTE FIRMADO SIN SOBRE)
$FACTRONICA["DTEFIRMADO"]="FOLIO13179TIPO46_DTEFIRMADO.xml";
# 
# 
# 
#NOMBRE DE LOS ARCHIVOS DE SALIDA
$FACTRONICA["TRACKID"]="AEC_33333333K_TIPO46_FOLIO13179_CESION_TRACKID_RUT.xml";
$FACTRONICA["DTECEDIDOPORFIRMAR"]="AEC_33333333K_TIPO46_FOLIO13179_DTECEDIDOPORFIRMAR.xml";
$FACTRONICA["DTECEDIDOFIRMADO"]="AEC_33333333K_TIPO46_FOLIO13179_DTECEDIDOFIRMADO.xml";
$FACTRONICA["CESIONPORFIRMAR"]="AEC_33333333K_TIPO46_FOLIO13179_CESIONPORFIRMAR.xml";
$FACTRONICA["CESIONFIRMADA"]="AEC_33333333K_TIPO46_FOLIO13179_CESIONFIRMADA.xml";
$FACTRONICA["DOCUMENTOAECPORFIRMAR"]="AEC_33333333K_TIPO46_FOLIO13179_DOCUMENTOAECPORFIRMAR.xml";
$FACTRONICA["DOCUMENTOAECFIRMADO"]="AEC_33333333K_TIPO46_FOLIO13179_DOCUMENTOAECFIRMADO.xml";
# 
# 
# 
#CONFIGURACIÓN DEL SERVIDOR DE FACTURACIÓN
$FACTRONICA["URLHOST"]="https://www.suservidor.cl/factronica_cederfactura/cesion_recibe_txt.php";
$FACTRONICA["URLFILE"]="cesion_recibe_txt.php";
$FACTRONICA["PORT"]="80";
$FACTRONICA["VERBOSE"]="1";
$FACTRONICA["RETURNTRANSFER"]="1";
$FACTRONICA["TIMEOUT"]="30";
$FACTRONICA["HEADER"]="0";
$FACTRONICA["HEADER_OUT"]="1";
# 
# 
# 
#DATOS DE CARATULA
$DocumentoAEC["ID"]="AEC_33333333K_TIPO46_FOLIO13179_ID_AEC";
$Caratula["RutCedente"]="11111111-1";
$Caratula["RutCesionario"]="22222222-2";
$Caratula["NmbContacto"]="FACTOTAL S.A.";
$Caratula["FonoContacto"]="226855900";
$Caratula["MailContacto"]="pnorambuena@ft.cl";
# 
# 
# 
#DATOS DEL CESION
$DocumentoCesion["ID"]="AEC_33333333K_TIPO46_FOLIO13179_ID_DOC";
$DocumentoCesion["SeqCesion"]="1";
# 
# 
# 
#DATOS DEL DTE
$IdDTE["TipoDTE"]="46";
$IdDTE["RUTEmisor"]="11111111-1";
$IdDTE["RUTReceptor"]="33333333-K";
$IdDTE["Folio"]="13179";
$IdDTE["FchEmis"]="2022-01-31";
$IdDTE["MntTotal"]="43970850";
# 
# 
# 
#DATOS DEL CEDENTE
$Cedente["RUT"]="11111111-1";
$Cedente["RazonSocial"]="EXPORTADORA PRUEBAS LTDA";
$Cedente["Direccion"]="LAS TOSCAS RUTA L-25 KM.7";
$Cedente["eMail"]="dte@SERVIDOR.cl";
$Cedente["RUTAutorizado"]="8894929-3";
$Cedente["Nombre"]="PERICO LOS PALOTES";
$Cedente["DeclaracionJurada"]="Yo PERICO LOS PALOTES, Rut 8894929-3,en representación de EXPORTADORA PRUEBAS LTDA, RUT 11111111-1 declaro bajo juramento que he puesto a disposición del cesionario FACTOTAL S.A, RUT 22222222-2, el (los) documento(s) donde constan los recibos de la recepción de las mercaderías entregadas o servicios prestados, entregados por parte del deudor de la factura  EXPORTADORA PRUEBAS LTDA,   Rut 11111111-1, de acuerdo a lo establecido en la Ley N° 19.983.";
# 
# 
# 
#DATOS DEL CESIONARIO
$Cesionario["RUT"]="22222222-2";
$Cesionario["RazonSocial"]="FACTOTAL S.A";
$Cesionario["Direccion"]="ANDRES BELLO 2233 PROVIDENCIA";
$Cesionario["eMail"]="pnorambuena@ft.cl";
# 
# 
# 
#DATOS DEL DOCUMENTO CEDIDO
$DocumentoCesion["MontoCesion"]="43970850";
$DocumentoCesion["UltimoVencimiento"]="2022-01-31";
$DocumentoCesion["eMailDeudor"]="dte@SERVIDOR.cl";
# 
# 
# 
#CONFIGURACION DE NOMBRES DE CARPETAS Y ARCHIVOS
$DocumentoDTECedido["ID"]="AEC_33333333K_TIPO46_FOLIO13179_DTEURI";
# 
# 
# 
#CARGAR CERTIFICADO DIGITAL

$certificado["Modulus"]="3pr2gEoi8LFOTEy12/ukLkvexoKehCkHFtf1509I6kv0qvIt/i2p6DUFTeDwHFOS
OOfuyYAEJ2bbYQIKy1SUtIqXDUqVUuXv/WNvOniYuNphjgBsbhR+mMXk4ISg9zgh
v/h38+c/b6edZSzqmSS+mzHYsXOgUytvl/VgZOW0A9U=";# MODULO DEL CERTIFICADO

$certificado["Exponent"]="AQAB";# EXPONENTE DEL CERTIFICADO

$certificado["X509Certificate"]="MIIGPTCCBSWgAwIBAgIKWc3d+wAAABTyeDANBgkqhkiG9w0BAQUFADCB0jELMAkG
A1UEBhMCQ0wxHTAbBgNVBAgTFFJlZ2lvbiBNZXRyb3BvbGl0YW5hMREwDwYDVQQH
EwhTYW50aWFnbzEUMBIGA1UEChMLRS1DRVJUQ0hJTEUxIDAeBgNVBAsTF0F1dG9y
aWRhZCBDZXJ0aWZpY2Fkb3JhMTAwLgYDVQQDEydFLUNFUlRDSElMRSBDQSBGSVJN
I58feqvx9hkoA60VqZ7wd70AJkQCw6MQKk4Td2KVUp4P85CPljjTo/GEnjAP4LQD
P4kAZwkYPOeCxl1Ird/BZcvYgh6Jz2H9FgOqlYlY0Y2YaXucDEap0Etaz93N+jNC
VkuyuW0EdsozoMopnofyOc4=";# X509 DEL CERTIFICADO

$certificado["PrivKey"]="-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQDemvaASiLwsU5MTLXb+6QuS97Ggp6EKQcW1/XnT0jqS/Sq8i3+
bfrUeLdp+Mqc4HUzOadXb5H+zshkcOkoalTIAGznqHAvusCjFkCdwJe2ZdT9JcrR
amcZXyTW7DoEW6HC5wJBAOW/F3berpKSbthzJNZGBdUZOYwlDK80sDDxB4TI0jL+
MWphHeiyKBw/IlE3uCcWQqkSexW6E0sfaVA6iBl/xjM=
-----END RSA PRIVATE KEY-----";# LLAVE PRIVADA DEL CERTIFICADO
?>
